title: Volunthree
description: Organization page for Volunthree
remote_theme: pages-themes/minimal@v0.2.0
google_analytics:
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/volunthree/volunthree
plugins:
- jekyll-remote-theme
